### ISSUE TITLE
Category buttons

### ISSUE THREAD

**Issue by midzer** [lokal-ninja/ln-base#43]
Right now, category buttons are very crowded and thus not optimal clickable in mobile.

Try to adjust their CSS via:

```css
.categories > button {
    padding: 3px 6px;
    margin: 0 0.5rem 0.5rem 0;
}
```
